# Generated by Django 2.2.7 on 2020-12-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('RegName', models.CharField(help_text='Enter Registration customer name', max_length=5)),
                ('FaxNum', models.CharField(help_text='Enter Fax number', max_length=12)),
                ('PhNum', models.CharField(help_text='Enter Phone number', max_length=13, null=True)),
                ('Cus_num', models.CharField(help_text='Enter Customer Number', max_length=12, primary_key=True, serialize=False)),
            ],
        ),
    ]
