# Generated by Django 2.2.7 on 2020-12-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kepco_RPA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('Order', models.CharField(help_text='Contents Order Number', max_length=5, primary_key=True, serialize=False)),
                ('Main', models.TextField(help_text='real contents')),
            ],
        ),
    ]
